### ISSUE TITLE
Handle case when date of issue is Null

### ISSUE THREAD

**Issue by MalloZup** [MalloZup/doghub#5]
Somehow we need to catch if the Issue datetime isn for some reason null
```
INFO: comparing issue with tolleration time(days) :130
Exception in thread "main" java.lang.NullPointerException
	at org.joda.time.format.DateTimeFormatterBuilder$NumberFormatter.parseInto(DateTimeFormatterBuilder.java:1305)
	at org.joda.time.format.DateTimeFormatterBuilder$Composite.parseInto(DateTimeFormatterBuilder.java:2516)
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:925)
	at clj_time.format$parse.invokeStatic(format.clj:160)
	at clj_time.format$parse.invoke(format.clj:156)
	at doghub.core$compare_issue_with_tdays.invokeStatic(core.clj:35)
	at doghub.core$compare_issue_with_tdays.invoke(core.clj:32)
	at doghub.core$comment_all_old_issues.invokeStatic(core.clj:49)
	at doghub.core$comment_all_old_issues.invoke(core.clj:40)
	at doghub.core$_main.invokeStatic(core.clj:59)
	at doghub.core$_main.invoke(core.clj:57)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at doghub.core.main(Unknown Source)
```

**Comment by MalloZup** [comment]
I think it should be when rate-limit is there that we can't get the datetime
